name: payyo_sdk
description: SDK for payyo payment gateway. This SDK covers differnet RPC calls wrapped inside RPC method Entity.
version: 0.0.5
homepage: https://github.com/nirman-lab/payyo-dart-sdk

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  crypto: ^2.1.5
  http: ^0.12.1
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

